@extends('layouts.app')
@section('title', 'Secure Feedback Hub')
@section('content')
<div class="row g-4 g-lg-5">
<section class="col-lg-5"><p class="eyebrow muted">Pertemuan 03 · Secure Feedback Hub</p><h1 class="display-5 fw-bold">Masukan akademik<br>untuk ITS.</h1><p class="lead mt-4">Sampaikan kritik, gagasan, atau saran mengenai akademik, sarana prasarana, dan kegiatan mahasiswa.</p><p class="muted">Form ini latihan lokal. Masukan hanya tampil dalam konfirmasi sesi dan tidak dikirim ke departemen.</p>
<div class="card p-4 mt-4"><h2 class="h5">Evaluasi saran Narafin (opsional)</h2><p>Jika membahas rancangan Agentic AI, tambahkan mode permainan dan indikator di bawah.</p><p class="mb-0">Contoh: kas simulasi turun dari 20 ke 12 koin sementara 4 dari 10 bahan terpakai. Apakah saran memakai bukti yang cukup?</p></div>
<p class="muted mt-4">Capaian W3: validasi masukan, email ITS, CSRF, dan CAPTCHA. Berikutnya di W4: demo perhitungan metrik simulasi.</p>
<p class="muted">Referensi: <a href="{{ $profil['ai']['sumber'] }}" target="_blank" rel="noopener">Narafin · Analitika Pemain, bagian Saran</a>. Integrasi LLM masih direncanakan.</p></section>
<div class="col-lg-7"><form method="POST" action="{{ route('feedback.store') }}" class="card p-4 p-md-5">
@csrf
@if($errors->any())<div class="alert alert-danger" role="alert">Masukan belum diproses. Periksa kolom yang ditandai di bawah.</div>@endif
<div class="mb-3"><label for="nama" class="form-label">Nama mahasiswa</label><input id="nama" name="nama" class="form-control @error('nama') is-invalid @enderror" value="{{ old('nama') }}" minlength="3" maxlength="100" autocomplete="name" aria-describedby="nama-error" required>@error('nama')<p id="nama-error" class="invalid-feedback">{{ $message }}</p>@enderror</div>
<div class="mb-3"><label for="email" class="form-label">Email mahasiswa ITS</label><input id="email" name="email" type="email" class="form-control @error('email') is-invalid @enderror" value="{{ old('email') }}" maxlength="254" placeholder="nama@student.its.ac.id" autocomplete="email" aria-describedby="email-error" required>@error('email')<p id="email-error" class="invalid-feedback">{{ $message }}</p>@enderror</div>
<fieldset class="border rounded-3 p-3 mb-3"><legend class="float-none w-auto px-2 fs-6">Konteks Narafin (opsional)</legend><p class="muted small">Isi keduanya hanya bila masukan membahas saran permainan.</p>
<div class="mb-3"><label for="mode_permainan" class="form-label">Mode permainan</label><select id="mode_permainan" name="mode_permainan" class="form-select @error('mode_permainan') is-invalid @enderror" aria-describedby="mode-error"><option value="">Tanpa konteks permainan</option>@foreach(['pemula' => 'Pemula', 'mahir' => 'Mahir'] as $value => $label)<option value="{{ $value }}" @selected(old('mode_permainan') === $value)>{{ $label }}</option>@endforeach</select>@error('mode_permainan')<p id="mode-error" class="invalid-feedback">{{ $message }}</p>@enderror</div>
<div><label for="indikator" class="form-label">Indikator saran yang dievaluasi</label><select id="indikator" name="indikator" class="form-select @error('indikator') is-invalid @enderror" aria-describedby="indikator-error"><option value="">Tanpa indikator</option>@foreach($profil['ai']['indikator'] as $value => $label)<option value="{{ $value }}" @selected(old('indikator') === $value)>{{ $label }}</option>@endforeach</select>@error('indikator')<p id="indikator-error" class="invalid-feedback">{{ $message }}</p>@enderror</div></fieldset>
<div class="mb-3"><label for="kategori" class="form-label">Kategori masukan</label><select id="kategori" name="kategori" class="form-select @error('kategori') is-invalid @enderror" aria-describedby="kategori-error" required><option value="">Pilih kategori</option>@foreach($kategori as $item)<option value="{{ $item }}" @selected(old('kategori') === $item)>{{ $item }}</option>@endforeach</select>@error('kategori')<p id="kategori-error" class="invalid-feedback">{{ $message }}</p>@enderror</div>
<div class="mb-3"><label for="pesan" class="form-label">Isi pesan</label><textarea id="pesan" name="pesan" rows="4" class="form-control @error('pesan') is-invalid @enderror" placeholder="Tuliskan masukan akademik atau evaluasi saran." minlength="15" maxlength="5000" aria-describedby="pesan-error" required>{{ old('pesan') }}</textarea>@error('pesan')<p id="pesan-error" class="invalid-feedback">{{ $message }}</p>@enderror</div>
<div class="mb-4"><label for="captcha" class="form-label">Berapakah {{ $captcha[0] }} + {{ $captcha[1] }}?</label><input id="captcha" name="captcha" type="number" step="1" class="form-control @error('captcha') is-invalid @enderror" value="{{ old('captcha') }}" aria-describedby="captcha-error" required>@error('captcha')<p id="captcha-error" class="invalid-feedback">{{ $message }}</p>@enderror</div>
<button class="btn btn-primary btn-lg">Kirim masukan</button>
</form></div></div>
@endsection
