@extends('layouts.app')
@section('title', 'Secure Feedback Hub')
@section('content')
<p class="eyebrow">Secure Feedback Hub</p><h1 class="mt-3 text-4xl font-bold">Masukan akademik untuk ITS</h1><p class="mt-4 max-w-3xl">Sampaikan saran mengenai akademik, sarana prasarana, atau kegiatan mahasiswa. Masukan hanya ditampilkan dalam konfirmasi sesi browser.</p>
<form method="POST" action="{{ route('feedback.store') }}" class="mt-8 grid max-w-3xl gap-5 rounded-2xl bg-white p-6 shadow-sm dark:bg-slate-900">@csrf
@if($errors->any())<p class="rounded-lg bg-red-100 p-3 text-red-800" role="alert">Periksa kolom yang ditandai sebelum mengirim.</p>@endif
@foreach(['nama' => 'Nama mahasiswa', 'email' => 'Email mahasiswa ITS'] as $key => $label)<label class="grid gap-2">{{ $label }}<input class="rounded-lg border border-slate-300 p-3 text-slate-900" name="{{ $key }}" type="{{ $key === 'email' ? 'email' : 'text' }}" value="{{ old($key) }}" required></label>@error($key)<p class="text-red-700">{{ $message }}</p>@enderror @endforeach
<label class="grid gap-2">Kategori masukan<select name="kategori" class="rounded-lg border border-slate-300 p-3 text-slate-900" required><option value="">Pilih kategori</option>@foreach($kategori as $item)<option value="{{ $item }}" @selected(old('kategori') === $item)>{{ $item }}</option>@endforeach</select></label>@error('kategori')<p class="text-red-700">{{ $message }}</p>@enderror
<fieldset class="grid gap-4 rounded-xl border border-slate-300 p-4"><legend class="px-2 font-semibold">Konteks Narafin (opsional)</legend><label class="grid gap-2">Mode permainan<select name="mode_permainan" class="rounded-lg border border-slate-300 p-3 text-slate-900"><option value="">Tanpa konteks</option>@foreach(['pemula' => 'Pemula', 'mahir' => 'Mahir'] as $value => $label)<option value="{{ $value }}" @selected(old('mode_permainan') === $value)>{{ $label }}</option>@endforeach</select></label>@error('mode_permainan')<p class="text-red-700">{{ $message }}</p>@enderror<label class="grid gap-2">Indikator<select name="indikator" class="rounded-lg border border-slate-300 p-3 text-slate-900"><option value="">Tanpa indikator</option>@foreach($profil['ai']['indikator'] as $value => $label)<option value="{{ $value }}" @selected(old('indikator') === $value)>{{ $label }}</option>@endforeach</select></label>@error('indikator')<p class="text-red-700">{{ $message }}</p>@enderror</fieldset>
<label class="grid gap-2">Isi pesan<textarea name="pesan" rows="5" class="rounded-lg border border-slate-300 p-3 text-slate-900" minlength="15" required>{{ old('pesan') }}</textarea></label>@error('pesan')<p class="text-red-700">{{ $message }}</p>@enderror
<label class="grid gap-2">Berapakah {{ $captcha[0] }} + {{ $captcha[1] }}?<input name="captcha" type="number" step="1" class="rounded-lg border border-slate-300 p-3 text-slate-900" value="{{ old('captcha') }}" required></label>@error('captcha')<p class="text-red-700">{{ $message }}</p>@enderror
<button class="rounded-xl bg-sky-900 px-5 py-3 font-semibold text-white">Kirim masukan</button></form>
@endsection
