@extends('layouts.app')
@section('title', 'Beranda')
@section('content')
<x-status-banner class="mb-8">Selamat datang, {{ $user }}!</x-status-banner>
<section class="hero-panel grid gap-8 p-7 md:grid-cols-[1.4fr_1fr] md:items-end md:p-12">
    <div><p class="text-xs font-extrabold uppercase tracking-[.18em] text-teal-200">Ruang akademik · Teknik Informatika ITS</p><h1 class="mt-6 max-w-3xl text-4xl font-bold leading-tight tracking-tight md:text-6xl">Belajar, merancang,<br>dan membangun.</h1><p class="mt-6 max-w-2xl text-lg text-sky-100">Saya {{ $profil['nama'] }}. Jelajahi profil akademik, eksperimen Laravel, dan rancangan Narafin AI Coach.</p><div class="mt-7 flex flex-wrap gap-3"><a class="rounded-xl bg-white px-5 py-3 font-bold text-slate-950 transition hover:bg-teal-100" href="{{ route('idea') }}#demo-saran">Coba demo saran</a><a class="rounded-xl border border-white/50 px-5 py-3 font-bold text-white transition hover:bg-white/10" href="{{ route('profile') }}">Lihat profil</a></div></div>
    <div class="rounded-2xl border border-white/20 bg-white/10 p-6 backdrop-blur-sm"><p class="text-xs font-bold uppercase tracking-widest text-teal-200">Saat ini di aplikasi</p><ul class="mt-5 space-y-4 text-sm"><li class="flex items-start gap-3"><span class="text-teal-300">●</span><span>Demo saran dari metrik permainan</span></li><li class="flex items-start gap-3"><span class="text-teal-300">●</span><span>Validasi formulir dan CAPTCHA</span></li><li class="flex items-start gap-3"><span class="text-teal-300">●</span><span>Routing, dashboard, dan kalkulator</span></li></ul><p class="mt-6 border-t border-white/20 pt-4 text-xs text-sky-100">NRP {{ $profil['nrp'] }} · {{ $profil['departemen'] }}</p></div>
</section>
<div class="mt-12 flex flex-wrap items-end justify-between gap-4"><div><p class="eyebrow">Jelajahi aplikasi</p><h2 class="mt-2 text-3xl font-bold tracking-tight">Mulai dari fitur yang Anda butuhkan</h2></div><a class="text-link" href="{{ route('about') }}">Tentang aplikasi →</a></div>
<div class="mt-6 grid gap-5 md:grid-cols-3"><article class="feature-card"><p class="eyebrow">01 / Analitika</p><h3 class="mt-4 text-xl font-bold">Narafin AI Coach</h3><p class="mt-3 text-slate-600 dark:text-slate-300">{{ $profil['ai']['capaian'] }}</p><a class="text-link mt-6" href="{{ route('idea') }}#demo-saran">Coba demo →</a></article><article class="feature-card"><p class="eyebrow">02 / Akademik</p><h3 class="mt-4 text-xl font-bold">Profil & kalkulator</h3><p class="mt-3 text-slate-600 dark:text-slate-300">Lihat riwayat belajar dan hitung rata-rata IP dua semester.</p><a class="text-link mt-6" href="{{ route('ipk.form') }}">Hitung IPK →</a></article><article class="feature-card"><p class="eyebrow">03 / Masukan</p><h3 class="mt-4 text-xl font-bold">Secure Feedback Hub</h3><p class="mt-3 text-slate-600 dark:text-slate-300">Sampaikan saran dengan validasi email ITS dan pemeriksaan matematika.</p><a class="text-link mt-6" href="{{ route('feedback.create') }}">Tulis masukan →</a></article></div>
<section class="mt-10 rounded-2xl border border-teal-200 bg-teal-50 p-6 dark:border-teal-900 dark:bg-teal-950/40"><p class="eyebrow">Rancangan proyek</p><h2 class="mt-2 text-2xl font-bold">Dari angka menjadi saran yang bisa ditinjau</h2><p class="mt-3 max-w-3xl text-slate-600 dark:text-slate-300">Instruktur memilih sesi, aplikasi menghitung metrik, dan integrasi AI direncanakan untuk menjelaskan hasil berdasarkan bukti. Demo saat ini memakai aturan lokal yang transparan.</p><a class="text-link mt-5" href="{{ route('idea') }}#alur">Lihat alur rancangan →</a></section>
@endsection
